version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 10
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
      - ls -ltr
      - export PR=$(echo $CODEBUILD_SOURCE_VERSION | cut -d / -f2)
      - echo $PR
      - export BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }'
      - if [ "X$BRANCH" = "X" ] ; then BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')"; export BRANCH=${BRANCH#remotes/origin/}; fi
      - echo $BRANCH
      - export CLEANBRANCH=$(echo $BRANCH | tr -cd [:alnum:])
      - echo $CLEANBRANCH
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
